#! /bin/sh

export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

. "${HOME}/.cache/wal/colors.sh"

bspc monitor --reset-desktops 一 二 三 四 五 六 七 八 九 十

bspc config border_width		5 

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc rule -a Nightly state=tiled
bspc rule -a Nightly:Dialog state=floating
bspc rule -a Nightly:Prompt state=floating

bspc rule -a URxvt:scratch state=floating rectangle=800x600+560+300 sticky=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a discord:* desktop='^10' state=fullscreen

# generic rules
bspc rule -a Dialog state=floating
bspc rule -a Prompt state=floating

bspc config focused_border_color		"$color2"
bspc config active_border_color			"$color1"
bspc config normal_border_color			"$color1"

if [ "$1" = "reload" ]; then
	echo "reloaded config."
else
	"$BSPWM_CONFIG/autostart" &
	"$HOME/.scripts/toggle-gaps.sh" gaps &
fi
